name: flutter_get_ride_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  flutter_dotenv: ^5.2.1
  dio: ^5.7.0
  logging: ^1.3.0
  flutter_screenutil: ^5.9.3
  dartz: ^0.10.1
  get_it: ^8.0.0
  shared_preferences: ^2.3.2
  intl: any
  flutter_localizations:
    sdk: flutter
  http: ^1.2.2
  # flutter_localizations:
  #   sdk: flutter
  # intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true


  assets:
    - .env.development
    - .env.staging
    - .env.production
    - assets/icons/
    - assets/images/